# views.py

import re
from functools import lru_cache
from typing import Dict

from django.urls import URLPattern
from django.urls import URLResolver
from drf_spectacular.utils import OpenApiParameter
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

BASE_URL = "http://localhost:8080"


def clean_path(path: str) -> str:
    """
    Strip out the regex format content auto-generated by DRF, turning it into a plain RESTful URL path.
    """

    # Remove the format suffix match: \.(?P<format>xxx)
    path = re.sub(r'\\\.\(\?P<format>[^)]+\)', '', path)

    # Remove the parenthesized format match
    path = re.sub(r'\(\?P<format>[^)]+\)', '', path)

    # Remove the DRF regex parameter part (?P<param>pattern)
    path = re.sub(r'\(\?P<\w+>[^)]+\)', '{param}', path)

    # If there are multiple parenthesis-wrapped regex groups (e.g. prefix paths), strip the optional wrapper
    path = re.sub(r'\(\(([^)]+)\)\?\)', r'\1', path)  # ((...))? => ...

    # Remove the leading/trailing ^ and $
    path = path.replace('^', '').replace('$', '')

    # Remove the trailing ?/
    path = re.sub(r'\?/?$', '', path)

    # Remove backslashes
    path = path.replace('\\', '')

    # Collapse multiple slashes
    path = re.sub(r'/+', '/', path)

    # Add a leading slash, strip extra whitespace
    path = path.strip()
    if not path.startswith('/'):
        path = '/' + path
    if not path.endswith('/'):
        path += '/'

    return path


def extract_resource_paths(urlpatterns, prefix='/api/v1/') -> Dict[str, Dict[str, str]]:
    resource_map = {}

    for pattern in urlpatterns:
        if isinstance(pattern, URLResolver):
            nested_prefix = prefix + str(pattern.pattern)
            resource_map.update(extract_resource_paths(pattern.url_patterns, nested_prefix))

        elif isinstance(pattern, URLPattern):
            callback = pattern.callback
            actions = getattr(callback, 'actions', {})
            if not actions:
                continue

            if 'get' in actions and actions['get'] == 'list':
                path = clean_path(prefix + str(pattern.pattern))

                # Try to get the resource name
                name = pattern.name
                if name and name.endswith('-list'):
                    resource = name[:-5]
                else:
                    resource = path.strip('/').split('/')[-1]

                # Don't force-append an "s"; keep the resource name as-is otherwise
                resource = resource if resource.endswith('s') else resource + 's'

                # Get the View class and the model's verbose_name
                view_cls = getattr(callback, 'cls', None)
                model = None

                if view_cls:
                    queryset = getattr(view_cls, 'queryset', None)
                    if queryset is not None:
                        model = getattr(queryset, 'model', None)
                    else:
                        # Some Views use get_queryset()
                        try:
                            instance = view_cls()
                            qs = instance.get_queryset()
                            model = getattr(qs, 'model', None)
                        except Exception:
                            pass

                if not model:
                    continue

                app = str(getattr(model._meta, 'app_label', ''))
                verbose_name = str(getattr(model._meta, 'verbose_name', ''))
                resource_map[resource] = {
                    'path': path,
                    'app': app,
                    'verbose_name': verbose_name,
                    'description': model.__doc__.__str__()
                }

    print("Extracted resource paths:", list(resource_map.keys()))
    return resource_map


def param_dic_to_param(d):
    return OpenApiParameter(
        name=d['name'], location=d['in'],
        description=d['description'], type=d['type'], required=d.get('required', False)
    )


@lru_cache()
def get_full_resource_map():
    from jumpserver.urls import resource_api
    resource_map = extract_resource_paths(resource_api)
    print("Building URL for resource:", resource_map)
    return resource_map
