on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release And Upload assets

jobs:
  create-realese:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          TAG=$(basename ${GITHUB_REF})
          VERSION=${TAG/v/}
          wget https://raw.githubusercontent.com/matheus-marques-ft/js-installer/main/quick_start.sh
          sed -i "s@^GITHUB_HOST=.*@GITHUB_HOST=https://github.com@" quick_start.sh
          sed -i "s@^GITHUB_OWNER=.*@GITHUB_OWNER=matheus-marques-ft@" quick_start.sh
          sed -i "s@^REPO_PREFIX=.*@REPO_PREFIX=js-@" quick_start.sh
          sed -i "s@^INSTALLER_REPO=.*@INSTALLER_REPO=installer@" quick_start.sh
          sed -i "s@^VERSION=.*@VERSION=v${VERSION}@" quick_start.sh
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-config.yml
          version: ${{ steps.get_version.outputs.TAG }}
          tag: ${{ steps.get_version.outputs.TAG }}
      - name: Upload Quick Start Script
        run: gh release upload ${{ steps.get_version.outputs.TAG }} ./quick_start.sh -R $GITHUB_REPOSITORY --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Release
        run: |
          case "${{ steps.get_version.outputs.TAG }}" in
            *-stable) PRERELEASE=false ;;
            *)        PRERELEASE=true ;;
          esac
          gh release edit ${{ steps.get_version.outputs.TAG }} --draft=false --prerelease=$PRERELEASE -R $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
