on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release And Upload assets

jobs:
  create-realese:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          TAG=$(basename ${GITHUB_REF})
          VERSION=${TAG/v/}
          wget https://raw.githubusercontent.com/matheus-marques-ft/js-installer/main/quick_start.sh
          sed -i "s@^GITHUB_HOST=.*@GITHUB_HOST=https://github.com@" quick_start.sh
          sed -i "s@^GITHUB_OWNER=.*@GITHUB_OWNER=matheus-marques-ft@" quick_start.sh
          sed -i "s@^REPO_PREFIX=.*@REPO_PREFIX=js-@" quick_start.sh
          sed -i "s@^INSTALLER_REPO=.*@INSTALLER_REPO=installer@" quick_start.sh
          sed -i "s@^VERSION=.*@VERSION=v${VERSION}@" quick_start.sh
          echo "::set-output name=TAG::$TAG"
          echo "::set-output name=VERSION::$VERSION"
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-config.yml
          version: ${{ steps.get_version.outputs.TAG }}
          tag: ${{ steps.get_version.outputs.TAG }}
      - name: Upload Quick Start Script
        id: upload-release-quick-start-shell
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./quick_start.sh
          asset_name: quick_start.sh
          asset_content_type: application/text
      - name: Publish Release
        run: gh release edit ${{ steps.get_version.outputs.TAG }} --draft=false -R $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
